apiVersion: apps/v1
kind: Deployment
metadata:
  name: nina-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nina-api
  template:
    metadata:
      labels:
        app: nina-api
    spec:
      containers:
        - name: net-front
          image: AWS_ECR_REGISTRY/AWS_ECR_REPOSITORY:latest
          ports:
            - containerPort: 8081

