name: api-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  constant:
    runs-on: ubuntu-latest
    outputs:
      go-version: ${{ steps.constant.outputs.go-version }}
      aws-region: ${{ steps.constant.outputs.aws-region }}
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.0.0
      - id: constant
        name: constant
        uses: ./.github/workflows/composite/constant

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [ constant ]
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.0.0
      - id: go-build
        name: go build
        uses: ./.github/workflows/composite/go-build
        with:
          go-version: ${{ needs.constant.outputs.go-version }}
      - id: api-docker-build-and-push-image
        name: api docker build and push image
        uses: ./.github/workflows/composite/docker-build-and-push-image
        with:
          dockerfile-path: "."
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ needs.constant.outputs.aws-region }}
          aws-ecr-registry: ${{ secrets.AWS_ECR_REGISTRY }}
          aws-ecr-repository: nina-api-repository
      - id: envoy-docker-build-and-push-image
        name: envoy docker build and push image
        uses: ./.github/workflows/composite/docker-build-and-push-image
        with:
          dockerfile-path: "./envoy"
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: ${{ needs.constant.outputs.aws-region }}
          aws-ecr-registry: ${{ secrets.AWS_ECR_REGISTRY }}
          aws-ecr-repository: nina-envoy-repository

